version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - redis
    # Uncomment the following line if your PHP application requires a specific port to be exposed
    # ports:
    #   - "8000:8000"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"